# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "http_baklaga"

# TODO: define a target for each of your executables/libraries like this:
#[target.myexecutable]
#type = "executable" # static, shared
#sources = ["src/http_baklaga/*.cpp", "include/http_baklaga/*.hpp"]
#include-directories = ["include"]
#compile-features = ["cxx_std_11"]
#link-libraries = ["target-or-library"]
