# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "http_baklaga"

[options]
BAKLAGA_BUILD_EXAMPLES = true

[conditions]
build-examples = "BAKLAGA_BUILD_EXAMPLES"

[subdir.include]
[subdir.examples]