# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "http_baklaga"

[target.http_baklaga]
type = "interface"
include-directories = ["include"]
compile-features = ["cxx_std_20"]

[target.http_baklaga_example]
type = "executable"
sources = [
    "src/main.cpp",
    "include/**.ipp",
    "include/**.hpp",
]
link-libraries = ["http_baklaga"]
